---
before_install:
  - 'sudo apt-get --quiet update'
  - 'sudo apt-get --quiet --quiet install --no-install-recommends make rubber texlive-fonts-extra texlive-fonts-recommended texlive-latex-extra texlive-latex-recommended texlive-full'
script:
  - 'make build'

deploy:
  provider: 'releases'
  api_key:
    secure: 'axPgWO4iWe0r1cW5ImVBng6AQpZjCDFMbDBaOyR8mHi35IbrVjAYRCkyTpNnAZkeiukSn7dLA24M1MTvOzd25XSAR1Ak5ZQvoOVlsxSopVBio1NtTR/xFx4T4P1busQwhsX4m9LHcayoKBbaKF9BlPxR/3JJMOTB2ysJHVfdbBE='
  file: 'build/curriculum_vitae.pdf'
  skip_cleanup: true
  on:
    branch: 'master'
