---
name: 'Build'
on:
  pull_request: {}
  push:
    branches:
      - 'master'
    tags:
      - '*'
jobs:
  latex:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'xu-cheng/latex-action@v2'
        with:
          root_file: 'src/curriculum_vitae.tex'
          post_compile: 'latexmk -c src/curriculum_vitae.tex'
        env:
          TEXINPUTS: './lib:./src:'

      - uses: 'actions/upload-artifact@v2'
        with:
          path: 'curriculum_vitae.pdf'
          if-no-files-found: 'error'
      - if: "startsWith(github.ref, 'refs/tags/')"
        uses: 'softprops/action-gh-release@v1'
        with:
          files: 'curriculum_vitae.pdf'
          fail_on_unmatched_files: true

  release:
    needs:
      - 'latex'
    runs-on: 'ubuntu-latest'
    if: "github.ref == 'refs/heads/master'"
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'anothrNick/github-tag-action@1.35.0'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          DEFAULT_BUMP: 'none'
          INITIAL_VERSION: '1.0.0'
