---
name: 'Build'
on:
  pull_request: {}
  push:
    branches:
      - 'master'
jobs:
  latex:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'xu-cheng/latex-action@v2'
        with:
          root_file: 'src/curriculum_vitae.tex'
          post_compile: 'latexmk -c src/curriculum_vitae.tex'
        env:
          TEXINPUTS: './lib:./src:'
      - uses: 'actions/upload-artifact@v2'
        with:
          name: 'curriculum_vitae.pdf'
          path: 'curriculum_vitae.pdf'
          if-no-files-found: 'error'

  release:
    needs:
      - 'latex'
    runs-on: 'ubuntu-latest'
    if: "github.ref == 'refs/heads/master'"
    steps:
      - uses: 'actions/download-artifact@v2'
        with:
          name: 'curriculum_vitae.pdf'
      - id: 'date'
        run: 'echo "::set-output name=date::$(date +%Y%m%d)"'
      - uses: 'ncipollo/release-action@v1.8.6'
        with:
          artifactErrorsFailBuild: true
          artifacts: 'curriculum_vitae.pdf'
          commit: '${{ github.sha }}'
          tag: '${{ steps.date.outputs.date }}-${{ github.sha }}'
          token: '${{ secrets.GITHUB_TOKEN }}'
