---
name: 'Build'
on:
  pull_request: {}
  push:
    branches:
      - 'master'
jobs:
  latex:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'xu-cheng/latex-action@v2'
        with:
          root_file: 'src/main.tex'
          post_compile: 'latexmk -c src/main.tex'
        env:
          TEXINPUTS: './lib:./src:'
      - uses: 'actions/upload-artifact@v2'
        with:
          name: 'curriculum_vitae.pdf'
          path: 'main.pdf'
          if-no-files-found: 'error'

  release:
    needs:
      - 'latex'
    runs-on: 'ubuntu-latest'
    if: "github.ref == 'refs/heads/master'"
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/download-artifact@v2'
        with:
          name: 'curriculum_vitae.pdf'

      - id: 'version'
        run: |-
          echo "::set-output name=date::$(date +%Y%m%d)"
          echo "::set-output name=sha::$(git rev-parse --short HEAD)"
      - uses: 'ncipollo/release-action@v1.8.8'
        with:
          artifactErrorsFailBuild: true
          artifacts: 'curriculum_vitae.pdf'
          commit: '${{ github.sha }}'
          tag: '${{ steps.version.outputs.date }}-${{ steps.version.outputs.sha }}'
