---
name: 'Build'
on:
  pull_request: {}
  push:
    branches:
      - 'master'
jobs:
  latex:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'xu-cheng/latex-action@v3'
        with:
          root_file: 'src/main.tex'
          post_compile: 'latexmk -c src/main.tex'
        env:
          TEXINPUTS: './lib:./src:'
      - run: 'mv main.pdf curriculum_vitae.pdf'
      - uses: 'actions/upload-artifact@v4'
        with:
          name: 'curriculum_vitae.pdf'
          path: 'curriculum_vitae.pdf'
          if-no-files-found: 'error'

  release:
    needs:
      - 'latex'
    runs-on: 'ubuntu-latest'
    if: >-
      github.event_name == 'push'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/download-artifact@v4'
        with:
          name: 'curriculum_vitae.pdf'

      - id: 'version'
        run: |-
          echo "date=$(date +%Y%m%d%H%M)" >> "${GITHUB_OUTPUT}"
          echo "sha=$(git rev-parse --short HEAD)" >> "${GITHUB_OUTPUT}"
      - uses: 'ncipollo/release-action@v1.14.0'
        with:
          artifactErrorsFailBuild: true
          artifacts: 'curriculum_vitae.pdf'
          commit: '${{ github.sha }}'
          tag: '${{ steps.version.outputs.date }}-${{ steps.version.outputs.sha }}'
