---
name: 'Lint'
on:
  pull_request: {}
  push:
    branches:
      - 'master'
jobs:
  chktex:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'j2kun/chktex-action@1.0.3'
