---
name: 'Lint'
on:
  pull_request: {}
  push:
    branches:
      - 'master'
jobs:
  aspell:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'ktht/aspell@v2'
        with:
          args: '--conf ./aspell.conf'
  chktex:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'j2kun/chktex-action@1.0.3'
  yamllint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'ibiqlik/action-yamllint@v3'
