---
name: 'Release'
on:
  push:
    branches:
      - 'master'
jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'anothrNick/github-tag-action@1.35.0'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          DEFAULT_BUMP: 'none'
          INITIAL_VERSION: '1.0.0'
